### ISSUE TITLE
help, I need a implementation of javascript, try blake2s-js and 2b but failed

### ISSUE THREAD

**Issue by hunjixin** [dchest/blake256#2]
help, I need a implementation of javascript, try blake2s-js and 2b but failed.
mycode:

go
```
	a := blake256.New()
	a.Write(b)
	out := a.Sum(nil)
```

javascript   
```
var BLAKE2s =require("blake2s-js")
var h = new BLAKE2s(32);
h.update(buffer);
var bytes = h.digest();
```

input: [15 33 225 166 99 246 51 30 118 113 186 93 28 66 53 139 228 1 25 18 4 15]

blake2s-js:[107 99 155 28 223 30 12 217 177 165 208 55 1 27 47 144 185 209 80 60 100 29 116 162 233 215 254 121 198 58 132 10]

go:[43 125 161 199 94 72 17 229 152 31 139 141 168 136 56 196 66 231 47 94 87 110 147 160 91 40 166 165 17 30 164 60]

**Comment by dchest** [comment]
BLAKE-256 and BLAKE2s or BLAKE2b are different hash functions.

* Go implementation of BLAKE2s is here: https://github.com/dchest/blake2s
* JavaScript implementation of BLAKE2s is here: https://github.com/StableLib/stablelib/tree/master/packages/blake2s
* Go implementation of BLAKE2b is here: https://github.com/dchest/blake2s
* JavaScript implementation of BLAKE2b is here: https://github.com/StableLib/stablelib/tree/master/packages/blake2b

I'm not aware of JavaScript implementations of BLAKE-256.
